require('dotenv').config({path: '../../.env'});

const APPID = 95634255
const CONTRACT_ADDRESS = "6US7FPCF6FFK4NMN3IDBOOLDBV2HJL3AG2D4ZP5OYYUIFM4UQFBMAWYOGQ"

module.exports = {
  APPID,
  CONTRACT_ADDRESS,
}